### ISSUE TITLE
URL로 직접 접근 시 해당 URL의 컨텐츠가 아닌 메인 홈페이지 화면 노출

### ISSUE THREAD

**Issue by SehoNoh** [pythonkr/pyconkr2021dev#50]
안녕하세요, 스폰서 관련해서 메일로 커뮤니케이션하다가 URL 링크를 받았는데요
URL로 직접 접근 시 해당 URL의 컨텐츠가 아닌 메인 홈페이지의 컨텐츠가 노출되는 이슈가 있어서 제보드리게 됐습니다.

인프라가 자세히는 어떻게 구성되어 있는지는 모르겠지만
본 repo의 github workflow 파일과 현상으로 미루어 보았을때 SPA 다이나믹 라우팅에서 index를 찾지 못해 나는 현상인 거 같아서
S3 버킷 static website hosting 옵션에 error document 값이 index document 랑 같이 설정 되어있는지 확인 부탁드립니다.
(이 방법으로 해결이 안 될 수도 있습니다 (_ _))

![스크린샷 2021-07-05 오전 11 08 58](https://user-images.githubusercontent.com/1144643/124408543-68944800-dd81-11eb-8c73-4df5f779b90b.png)

항상 파이썬 커뮤니티 발전에 이바지 해주셔서 감사합니다.

**Comment by byung-u** [comment]
설정은 말씀해주신것처럼 동일하게 설정 되어있습니다.
* S3 버킷 static website hosting 옵션에 error document 값이 index document 랑 같이 설정

```
스폰서 관련해서 메일로 커뮤니케이션하다가 받으셨던 URL 링크
URL로 직접 접근 시 해당 URL의 컨텐츠가 아닌 메인 홈페이지의 컨텐츠가 노출되는 이슈
```
이 부분은 좀 더 확인해보겠습니다. 

제보해주셔서 감사합니다. 🙏

**Comment by constmoon** [comment]
해당 이슈는 cloudfront의 endpoint가 s3 static website endpoint 으로 설정되어있지 않아 발생한 문제였습니다.
현재는 수정하여 정상적으로 동작하는 것 확인했습니다.
감사합니다.
