### ISSUE TITLE
페이지, 컴포넌트 추가

### ISSUE THREAD

**Issue by golony6449** [pythonkr/pyconkr2021dev#59]
## 공지사항

- [x] 공지사항 컴포넌트(메인페이지)

## 후원사
- [x] 후원사 컴포넌트 (공통)
- [x] 후원사 상세 페이지

## 세션
- [x] 세션 페이지

**Comment by constmoon** [comment]
페이지와 컴포넌트 모두 구현되어 closed 합니다.
